name: artifact

on: push
 
jobs:
 ubuntu: 
  env:
    TEST: "get artifact"
  runs-on: ubuntu-latest
  steps: 
     - name: step one
       uses: actions/checkout@v4
     - name: step two
       uses: actions/upload-artifact@v4
       
     
  
 
