name: test_python

on: push
 
jobs:
 test:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: run
        run: python test.py

   
   
     
   
